name: StandardGroups
main: com.sbezboro.standardgroups.StandardGroups
version: 1.2.10
depend: [StandardPlugin]

commands:
    groups:
        description: Base command
        permission: standardgroups.groups
        permission-message: You don't have permission
        aliases: [g]

permissions:
    standardgroups.groups:
        default: true
    standardgroups.groups.admin:
        default: op
